base_url = "https://await.cl"
title = "Alvaro's Blog"
description = "A personal portfolio/blog website of Alvaro Parker del Fierro"

theme = "shadharon"

build_search_index = true

compile_sass = true
minify_html = true

taxonomies = [{ name = "tags", feed = true }]

[markdown]
highlight_code = true
highlight_theme = "css"

[extra]
toc = true
use_cdn = false
favicon = "/menu_icon/favicon.svg"
headerImage = "/menu_icon/profile_pic.jpg"

menu = [
    { name = "Projects", url = "/projects", weight = 1, icon = "projects.png" },
    { name = "About", url = "/about", weight = 2, icon = "profile_pic.jpg" },
]

socials = [
    { name = "linkedin", url = "https://www.linkedin.com/in/aparkerdf/", icon = "linkedin" },
    { name = "github", url = "https://github.com/AlvaroParker", icon = "github" },
    { name = "gitlab", url = "https://gitlab.com/AlvaroParker", icon = "gitlab" },
    { name = 'mail', url = 'mailto:aparkerdf@protonmail.com', icon = 'email' },
]
